export const directors = [
  {
    designation: "Director",
    name: "Nirob Devnath",
    institution: "Chittagong University (CU)",
    department: "Electrical & Electronic Engineering (EEE)",
    email: "nirobdevnatheee@gmail.com",
    url: "https://drive.google.com/uc?export=view&id=1BQtAhYb1jaZg594TVgPbMU0LcTdB4hDw",
  },
  {
    designation: "Co-Director",
    name: "Apurbo Kumar",
    institution:
      "Bangladesh University of Engineering and Technology (BUET) & Indian Institute Of Technology (IIT)",
    department:
      "Civil Engineering (CE) & Data Science and Artificial Intelligence (DS&AI)",
    email: "apurbokumar1355@gmail.com",
    url: "https://scontent.fdac181-1.fna.fbcdn.net/v/t39.30808-6/592313144_2008977396612926_5360946863699538642_n.jpg?_nc_cat=100&ccb=1-7&_nc_sid=1d70fc&_nc_eui2=AeEfykd8Z66fBRmh7UfZxUY8-LRTmjC3SJv4tFOaMLdIm6GS4abqygTqpZ36t5cEU41x67w-xwVxsW4FSh-nT7YZ&_nc_ohc=x8xTSlQJFiwQ7kNvwFhpQ-r&_nc_oc=Adp6wBVtLMlRoY_VNjFr_jNPI3CaH6HoeZHdv94zClgE_sK-TdPvC6gq6dFmd3z38Dg&_nc_zt=23&_nc_ht=scontent.fdac181-1.fna&_nc_gid=ccSQBVXaAllB4NAxtewP9g&_nc_ss=7b2a8&oh=00_Af6EBr2bugLiG1g5JTSkSVLr0FObWTgUSmxmyyMAbgjzig&oe=69FA4029",
  },
  {
    designation: "Co-Director",
    name: "Nafi Naib Mon",
    institution: "Islamic University Of Technology (IUT)",
    department: "Civil Engineering",
    email: "nafinaib668@gmail.com",
    url: "https://drive.google.com/thumbnail?id=129zlts1tHKu4Cms7-FiY1jgndDx7uZZs&sz=w800",
  },
];

export const administration = [
  {
    designation: "Treasurer",
    name: "Mahi Tasnim",
    institution: "Rajshahi University of Engineering and Technology (RUET)",
    department: "Architecture (Arch.)",
    email: "mahit9012@gmail.com",
    url: "https://drive.google.com/uc?export=view&id=1QI0Lu5ggkRzZokaKZdwvJQoxheIQQmST",
  },
  {
    designation: "Accounts & Finance Secretary",
    name: "Arafat Yeasmin Oyshi",
    institution: "Chittagong University",
    department: "B.B.A in Accounting",
    email: "yeasminoyshil8@gmail.com",
    url: "https://drive.google.com/uc?export=view&id=1Q4I8_ymZOGW9-FYMptVXXR5TOrraHBwm",
  },
  {
    designation: "Office Secretary",
    name: "Rudro Mohonto Jit",
    institution: "Rajshahi University of Engineering and Technology (RUET)",
    department: "Electrical and Electronic Engineering (EEE)",
    email: "rmjit01@gmail.com",
    url: "https://drive.google.com/uc?export=view&id=1FDNFbeYxpzHixmavrZJy82HtuvsF9Nt3",
  },
  {
    designation: "HR Secretary",
    name: " Torun Kumar Saha Tirtho",
    institution: "Brac University (BracU)",
    department: "Computer Science and Engineering (CSE)",
    email: "tirtho.saha007@gmail.com",
    url: "https://drive.google.com/uc?export=view&id=1go9sKblPeMqPaS_wwmGqpwsSJTXrhWBR",
  },
  {
    designation: "Assistant HR Secretary",
    name: "Diponna Roy",
    institution: "University Of Rajshahi",
    department: "Population Science & Human Resource Development",
    email: "diponna22@gmail.com",
    url: "https://drive.google.com/thumbnail?id=1Z2ivCF0YtVABIgECIj0_ExuxDNpZxJ7p&sz=w800",
  },
  {
    designation: "IR Secretary",
    name: "Abdullah Al Tahmid",
    institution: "Islamic University of Technology (IUT)",
    department: "Computer Science and Engineering (CSE)",
    email: "tahmidim99@gmail.com",
    url: null,
  },
  {
    designation: "IR Secretary (Assistant)",
    name: "Shreyosi Mohanta",
    institution: "North South University (NSU)",
    department: "Computer Science and Engineering (CSE)",
    email: "shreyosi.mohanta2312@gmail.com",
    url: null,
  },
  {
    designation: "IR Secretary (Assistant)",
    name: "Borsha Sarkar",
    institution: "Varendra University",
    department: "Department of English",
    email: "borshasarkar47@gmail.com",
    url: null,
  },
  {
    designation: "Event Management Secretary",
    name: "Md. Taufiq Biswas",
    institution: "Hajee Mohammad Danesh Science & Technology University (HSTU)",
    department: "Electronics and Communication Engineering (ECE)",
    email: "taufiq.a2002@gmail.com",
    url: "https://drive.google.com/uc?export=view&id=1MTGpKMsZrfBuvWo0UEeiv8Qxne8hOuP2",
  },
  {
    designation: "Event Management Secretary (Assistant)",
    name: "Mohammad Tafim Akondo",
    institution: "North South University (NSU)",
    department: "Electrical and Electronic Engineering (EEE)",
    email: "tafimmoula2324@gmail.com",
    url: "https://drive.google.com/thumbnail?id=103bb4u8F6BpCwTSqxDThlfotNvtxHmTH&sz=w800",
  },
  {
    designation: "Event Management Secretary (Assistant)",
    name: "Anik Kumar Ray",
    institution: "University of Dhaka (DU)",
    department: "Department of Statistics",
    email: "anikray050@gmail.com",
    url: "https://drive.google.com/uc?export=view&id=1NDqDI4snIHzjpMVsptU34hnZ_M7nIHo5",
  },
  {
    designation: "Organizing Secretary",
    name: "Majedul Hoque",
    institution: "University of Frontier Technology, Bangladesh (UFTB)",
    department: "Data Science and Engineering",
    email: "hoquemazed007@gmail.com",
    url: "https://drive.google.com/uc?export=view&id=1OXH827xYgQgGKAycqkYaQiRFVju4bOZc",
  },
];

export const research = [
  {
    designation: "Research Secretary (Admin)",
    name: "Samyo Pramanik",
    institution: "Bangladesh University of Engineering and Technology (BUET)",
    department: "Computer Science and Engineering (CSE)",
    email: "samyopramanik2003@gmail.com",
    url: "https://drive.google.com/uc?export=view&id=1N1bmCMhPLfJd-zTxt1iz2gRYNjFifKTn",
  },
  {
    designation: "Research Secretary (Coordination)",
    name: "Prachya Biswas",
    institution: "Brac University (BracU)",
    department: "Computer Science and Engineering (CSE)",
    email: "prachya.biswas@g.bracu.ac.bd",
    url: "https://drive.google.com/uc?export=view&id=1cdrzhe-8m_es9_jB9FS6PkuIxGOg2yha",
  },
  {
    designation: "Research Secretary (Documentation)",
    name: "Atiqur Rahman Atik",
    institution: "Bangladesh University of Engineering and Technology (BUET)",
    department: "Computer Science and Engineering (CSE)",
    email: "rahmanatikofc@gmail.com",
    url: "https://drive.google.com/uc?export=view&id=1dPOFLrQ08gNCnjvcTo9VNknCuHraNqJ5",
  },
  {
    designation: "Research Assistant",
    name: "Himel Sarker Turjo",
    institution: "Bangladesh University of Engineering and Technology (BUET)",
    department: "Urban and Regional Planning",
    email: "turjo2215027@gmail.com",
    url: "https://drive.google.com/thumbnail?id=16Vd7N7fbMkl9vrx3VhOTMRdZ_Z96OavB&sz=w800",
  },
  {
    designation: "Research Assistant",
    name: "Rajoy Nath",
    institution: "Chittagong University of Engineering and Technology (CUET)",
    department: "Mechatronics and Industrial Engineering",
    email: "rjnathanik@gmail.com",
    url: "https://drive.google.com/uc?export=view&id=1Qs7PYbd9UxG_rgIo2-uCWjw_YLMqtS72",
  },
  {
    designation: "Research Assistant",
    name: "MD Shahed Ahammod",
    institution: "University of Frontier Technology, Bangladesh (UFTB)",
    department: "Data Science and Engineering",
    email: "shahedahammod@gmail.com",
    url: null,
  },
  {
    designation: "Research Assistant",
    name: "Sarafat Islam Tonoy",
    institution: "Dhaka University (DU)",
    department: "Applied Statistics and Data Science (ASDS)",
    email: "sarafatislamtonoy@gmail.com",
    url: "https://drive.google.com/thumbnail?id=1heoWICIaQiyt3ewc4Qv_mCUqV9thNEyy&sz=w800",
    // url: "/api/proxy-image?id=",
  },
];

export const ict = [
  {
    designation: "ICT Director",
    name: "Muhaiminul Sadat",
    institution: "Bangladesh University of Engineering and Technology (BUET)",
    department: "Civil Engineering (CE)",
    email: "muhaiminulsadat@gmail.com",
    url: "https://avatars.githubusercontent.com/u/227270611?v=4",
  },
  {
    designation: "Designer (ICT Division)",
    name: "Shourob Biswas",
    institution: "Daffodil International University (DIU)",
    department: "Software Engineering",
    email: "shourob623483@gmail.com",
    url: "https://drive.google.com/uc?export=view&id=1xO_oINxM5zazIlCXerqzm_-AutCn41G_",
  },
  {
    designation: "Co-Designer (ICT Division)",
    name: "Md. Ashfik Sadman",
    institution: "Chittagong University of Engineering and Technology (CUET)",
    department: "Civil Engineering (CE)",
    email: "ashfiksadman2006@gmail.com",
    url: "https://drive.google.com/uc?export=view&id=1ZDS_l4wOd_6Yh6vkvdNDd40RStJ3bJ33",
  },
  {
    designation: "Co-Designer (ICT Division)",
    name: "Mithun Kumar Roy",
    institution:
      "Hajee Mohammad Danesh Science and Technology University (HSTU)",
    department: "Electronics and Communication Engineering",
    email: "mkrmithun23@gmail.com",
    url: "https://drive.google.com/uc?export=view&id=1ipCL7vS-oNLLBHnA7hJHbGpCyngcSU6p",
  },
];

export const law = [
  {
    designation: "Legal Secretary",
    name: "Al-Hadi Leon",
    institution: "Chittagong University",
    department: "Law",
    email: "ahlalhadi@gmail.com",
    url: "https://drive.google.com/thumbnail?id=1l11dzzH4y0udptP8-Eu1xIn2Na9m4Nin&sz=w800",
  },
  {
    designation: "Legal Researcher",
    name: "Ahonaf Shahriar Nadim",
    institution: "Chittagong University",
    department: "Law",
    email: "ahonaf.nadim1@gmail.com",
    url: "https://drive.google.com/thumbnail?id=1QL0Eqp9XfDdzYL1SE-gt3YlU256sBAAK&sz=w800",
  },
  {
    designation: "Legal Co-Ordinator",
    name: "Tanveer Hridoy",
    institution: "Chittagong University",
    department: "Law",
    email: "hstanvir@gmail.com",
    url: "https://drive.google.com/thumbnail?id=1dL3GAZZLtcMMu8SigIfO1n8C858umSX7&sz=w800",
  },
  {
    designation: "Assistant Legal Co-Ordinator",
    name: "Jahidul Islam Babu",
    institution: "Chittagong University",
    department: "Law",
    email: "mdjahidulislambabu2005@gmail.com",
    url: null,
  },
];

export const executives = [
  {
    designation: "Executive Member",
    name: "Asaduzzaman Riem",
    institution: "Chittagong University",
    department: "Electrical & Elctronic Engineering(EEE)",
    email: "azriem2000@gmail.com",
    url: "https://drive.google.com/thumbnail?id=1bcgPO-DcfyqsksdNyKMkzw2WIYeBNOcu&sz=w800",
  },
  {
    designation: "Executive Member",
    name: "Ruhul Amin Maruf",
    institution:
      "Hajee Mohammad Danesh Science and Technology University (HSTU)",
    department: "Electronics and Communication Engineering (ECE)",
    email: "ruhulamin43416@gmail.com",
    url: null,
  },
  {
    designation: "Executive Member",
    name: "Arpon Adhikary",
    institution: "Chittagong University",
    department: "Electrical & Electronic Engineering(EEE)",
    email: "arponadhikary2001@gmail.com",
    url: "https://drive.google.com/thumbnail?id=18nE2ElAeJi2JbHIUtD_5jdj1GcIKZmfO&sz=w800",
  },
  {
    designation: "Executive Member",
    name: "Farhan Labib Ahan",
    institution: "Dhaka university",
    department: "Computer Science & Engineering(CSE)",
    email: "farhanlabibahan@gmail.com",
    url: "https://drive.google.com/uc?export=view&id=1oMdJnLpMymvUTn7GiiKxGt-Ie5oWrlxn",
  },
  {
    designation: "Executive Member",
    name: "Chaion Das",
    institution:
      "Hajee Mohammad Danesh Science and Technology University (HSTU)",
    department: "Electronics and Communication Engineering (ECE)",
    email: "chayand063@gmail.com",
    url: "https://drive.google.com/thumbnail?id=1GHieuq1AU2cJZ6Sx5-MkBEVxSjSJNRW4&sz=w800",
  },
  {
    designation: "Executive Member",
    name: "Tahsin T. Talha",
    institution:
      "Hajee Mohammad Danesh Science and Technology University (HSTU)",
    department: "Electronics and Communication Engineering (ECE)",
    email: "tahsinttalha@gmail.com",
    url: null,
  },
  {
    designation: "Executive Member",
    name: "Niaz Nafis Shuvo",
    institution: "Brac University (BracU)",
    department: "Computer Science(CS)",
    email: "nn.shuvro.75@gmail.com",
    url: null,
  },
];

const panelMembers = {
  directors,
  administration,
  research,
  ict,
  law,
  executives,
};

export default panelMembers;
